In [3]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
iris.target_names


array(['setosa', 'versicolor', 'virginica'], dtype='|S10')

In [43]:
iris.target
# 0->I. setosa
# 1->I. versicolor
# 2-> I. virginica
# these are labels/species of the flowers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
iris.data
#gives us the features or description of the 150 varieties of the 3 labels

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
iris.data[0]
# example of the 0th index of the iris.data 2D array describing the characteristics 0th(first species) of the data set
#5.1-> sepal length (cm)
#3.5-> sepal width (cm)
#1.4-> petal length (cm)
#0.2-> petal width (cm)

array([5.1, 3.5, 1.4, 0.2])

In [19]:
for i in range (len(iris.target)):
    print("example %d, label: %s, features %s"%(i, iris.target[i],iris.data[i]))

example 0, label: 0, features [5.1 3.5 1.4 0.2]
example 1, label: 0, features [4.9 3.  1.4 0.2]
example 2, label: 0, features [4.7 3.2 1.3 0.2]
example 3, label: 0, features [4.6 3.1 1.5 0.2]
example 4, label: 0, features [5.  3.6 1.4 0.2]
example 5, label: 0, features [5.4 3.9 1.7 0.4]
example 6, label: 0, features [4.6 3.4 1.4 0.3]
example 7, label: 0, features [5.  3.4 1.5 0.2]
example 8, label: 0, features [4.4 2.9 1.4 0.2]
example 9, label: 0, features [4.9 3.1 1.5 0.1]
example 10, label: 0, features [5.4 3.7 1.5 0.2]
example 11, label: 0, features [4.8 3.4 1.6 0.2]
example 12, label: 0, features [4.8 3.  1.4 0.1]
example 13, label: 0, features [4.3 3.  1.1 0.1]
example 14, label: 0, features [5.8 4.  1.2 0.2]
example 15, label: 0, features [5.7 4.4 1.5 0.4]
example 16, label: 0, features [5.4 3.9 1.3 0.4]
example 17, label: 0, features [5.1 3.5 1.4 0.3]
example 18, label: 0, features [5.7 3.8 1.7 0.3]
example 19, label: 0, features [5.1 3.8 1.5 0.3]
example 20, label: 0, features

In [38]:
import numpy as np
test_idx = [0,50,100]
# remove from the dataset the first, 50th and 100th label for later testing the model
# training dataset 
train_target = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx, axis=0)



In [40]:
# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]


In [47]:
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier.fit(train_data, train_target)
print(test_target)

[0 1 2]


In [48]:
classifier.predict(test_data)

array([0, 1, 2])